#+TITLE: 04 Aug 2023 - Let's Talk About Frames!
#+DESCRIPTION: In the 1990's things were crazy and you never knew what browser would be best for a site...unless they told you ;)
#+AUTHOR: Jon Saxton
#+HTML_HEAD: <link href="../../styles/main.css" rel="stylesheet" type="text/css" />

First thing's first! I was accused of copying another person's new format just because I had three sections! That's right! [[http://onigirionegai.info/~yayoi][Yaya's World's (not old browser ready)]] news articles usually have three sections and my first blog article also had three sections, so what? That doesn't make them the same and I didn't copy her. It was just an interesting coincidence. Now on to the news of the week for this site. I've added a new sub-section to my [[file:../test.org][test page]] that talks about frames. There aren't any examples on that section, just a few code blocks and talking about frames and why they were used, but it is a new sub-section. I had thought about another new sub-section, the image map section, but I don't remember much about how that worked. I put up a little introduction, but no examples yet, I'll do some research and see what I can dig up and hope to add some examples and descriptions later. I'm also going to start writing a little PHP script that will serve as a guest book for this site. It will display guest book entries and have a form at the bottom for you do add new entries. I'll talk a bit more about how this is accomplished a little later after I introduce the guest book itself. The script will hopefully be ready by the time this article goes up.

There is one more thing. Blog posts are usually written before they are released. Like, Yaya, I try to do a few updates all at once, but unlike her, I'll usually start with a blog post. That means that the date stamp on the blog post might be different from the one that is shown on the bottom of the page and neither will reflect when the post comes out. The one in the title is when the post is written and the one at the bottom of the page is when it was last updated. I hope that doesn't confuse anyone. Also, every page that is created by Emacs will have a 'created' date. This is actually more of a 'last modified' date because it is updated every time a page is re-published, which happens after every update. Just thought I'd let you know.

Also! look no sections this time, I can be different! This is not written in my usual tone as I'm a little crazy right now because of [[https://www.youtube.com/channel/UCt9H_RpQzhxzlyBxFqrdHqA][Fuwamoco]] Mornings! Those doggos are too cute, and make me a little too hyper, but this is Jon, not Yaya! I wonder if I should sign everything "I am not Yaya, I am Jon" in honor of the adorable doggos Fuwawa and Mococo!
