#+TITLE: 06 Sep 2023 - Main Site Updates
#+DESCRIPTION: Explaining that I am now focusing on the main site while looking for the best way to publish this one
#+AUTHOR: Jon Saxton
#+HTML_HEAD: <link href="../../styles/main.css" rel="stylesheet" type="text/css" />

This site is essentially done for now. There may be a few things that I would like to set up in the future, but those will all probably take a lot of time and effort to research and complete. I am satisfied with what I have so far and will now be happy to figure out how I want to upload this to my server for all to see! Yes, none of the previous blog entries were available to read when they were written! I mostly wrote them for myself. Speaking of the server though, I /do/ have a site! And that site has seen a /big/ shift on what its about and its contents!
* The main site
#+ATTR_HTML: :target _top
The main site is called [[https://onigirionegai.info][Onigiri☆Onegai]]! It used to be a site set up for me to showcase stories done in a type of visual novel style using only HTML, JavaScript, and a splash of PHP. While the idea for this new type of web-based VN was, I believe and still believe, a good one, I don't have the patience or time to work on such large projects especially if I am doing all the work from, writing, to story boarding, to drawing, to programming. I had partners, but they are also busy and I just can't do it all myself. To be clear, I am not blaming them, I am also busy, it just led to a shift in what the site is and the type of content that is there.
* The updates!
So the main site will no longer be for hosting those web-based VNs, at least for the time being. Actually, the plan would be to give each VN its own site that would be styled to it specifically not a blanket site with a unified design. The main site is, therefore, transitioning to a site that:
1. Gives information about the people working on projects
2. Showcases other sites
3. Collects news about our members and projects
This is, mostly, already done. I am actually using Hugo to build that site because its easier to build with than using Emacs alone. I use Emacs here because I have the frames set up with, what is basically, a separate page for the navigation bar, so its easier to generate just directly from Emacs and org-mode than to build a whole modern site. Hugo is really better for that.
* What does this mean for this site?
Sadly, for the time being, I will be working on it less. Where possible, I will still be doing blog entries every week, but other pages and sections may not see as much work. Of course, as I said, much of it is in maintenance mode, so it isn't a big deal right now. I will also be looking at the best way to deploy this to the same server that is hosting the main site so all can see this testament to 90's design! Once I do that, I may look at building or sourcing, additional web applications, like maybe a forum. We shall see!
