#+TITLE: 09 Aug 2023 - Guestbook!
#+DESCRIPTION: In the 1990's guestbooks were rad!
#+AUTHOR: Jon Saxton
#+HTML_HEAD: <link href="../../styles/main.css" rel="stylesheet" type="text/css" />

Another week, another news article! This will be another fairly short article, but I think a lot of articles here will be pretty short unless I have other things to talk about then just this site. Well, first thing first, the [[file:../../apps/guestbook/index.php][Guestbook]] is up and working. You probably won't have a chance to see it, but there are already two entries! They were written by me though, just to test things. The reason you won't see them is they'll be deleted as soon as there are other entries in the guestbook. The functions of this little applet are finished and you can write your own entries now, so feel free to do so!
* More Linux stuff
Okay, I don't normally talk about this and probably won't talk about it much here, but there are a couple of things that are getting in the way of my recreating and exploring the vintage Internet experience. One of those things is a little experiment I am running on a Linux system I have kicking around. Its actually the system that runs this site (or ran it during testing if you are somehow reading this after the site is live). I am experimenting with Wayland and using Qtile as a Wayland Compositor. I spent far too much time the last couple of days working on getting Qtile configured. Fortunately that is mostly done. There are a couple of nitpicky things that I want to fix, but everything is functional. So far I like the new graphical environment and am using it to write this blog entry. I'll let you know if things change. The main reason for doing this was that Emacs/EXWM is a terrible window manager and I wanted to use the new protocol.
* Doctoral Dissertation
The other thing is that I am in a doctoral residency and preparing to propose a dissertation so I am doing a ton of research and writing. This, of course, takes a lot of my time. This is the priority, so that's why I'm saying to get used to short blog articles at least during this residency. I do plan on updating the site weekly, but they may only be small updates for now.
