#+TITLE: 11 Feb 2024 - Infinite Mac, Infinite Possibilities
#+DESCRIPTION: If you ever wondered what it was like to use a Mac around 1996, or any time in the early days, I have a site for you!
#+AUTHOR: Jon Saxton
#+HTML_HEAD: <link href="../../styles/main.css" rel="stylesheet" type="text/css" />

Well, I haven't updated our little 1996 web experience styled site in quite a while. To be fair, I haven't really updated the main site much either, but I digress. I am updating it today! This isn't going to be very long, as I am only really adding one new link to the sidebar over there, but I think it is definitely a good link to add now that I know about it. First though I think I want to reiterate something from the past lore of this site.

* The /True/ Origin of This Site
On the main page I stated that this site exists because I want to. That really is it, but there is a reason I decided to start writing a weird site like this and it isn't just because I got started building web sites back in the mid 90's. I mean that is part of it, but that's not the whole story.

I remember walking to a student store at the University of Colorado Boulder. I was there for a BSA activity. I was still quite young, maybe about 13 or 14. As I was walking around the store I, naturally, gravitated toward the laptops. I was trying to go for my Eagle Scout because I was promised a laptop if I was able to complete it. So, I guess I was really just reminding myself why I was there. Now laptops were cool little portable computers and they appealed to me ever since I first saw one in an old sitcom, or something. The problem is a lot of the laptops of this era were beige or black or like a dark gray. If you're lucky you might find a light gray laptop from the likes of Toshiba or Sony, but nothing was particularly colorful and they were all kinda bulky square things. Except, there was one at this store that was nothing like the rest. It was rounded, it was translucent white with little pinstripes and lime or orange or blue (I later found out it also came in red and purple) accents all of it. It was an iBook G3 from Apple. This was the laptop I wanted!

Sadly I never got that laptop. I never completed Eagle Scout and my first computer that was truly my own was a W-Series Sony VAIO. I wouldn't even have a Mac to call my own until I entered graduate school. However, the iBook G3, the iMac G3 we had in the high school tech lab, and MacOS 9 all called out to me. I only got to use MacOS 9 once for some web browsing and it had thing like a custom application launcher that the school added.

* MacOS 9 on OSX
I did eventually get that Mac. It was (or is actually) a 2021 M1 MacBook Air. It wasn't long before I learned I could run MacOS9 through in emulator on this thing. I even started emulating other Macs, like 6800k Mac running System 7.5. Problem is, I didn't really have much to do on these systems. Yet there was something oddly appealing about working with them. Sure I was able to run some games and even managed to get some software, but, I thought it would be cool to also take them online. Only the modern web doesn't play nice with old operating systems. Of course I heard about The Old Net and some of the other external sites in my side bar, but I wanted something else. I wanted to code something just as I did back then. So I wrote this site. That is how this site started. It was all because I wanted something to work on and then display in System 7.5!

* Infinite Mac
As I mentioned, I started this because I was emulating old Macintosh systems. It doesn't matter how I was emulating them or what I was using to emulate them. In fact, that matters even less because of the new website called the Infinite Mac. This is essentially a web-based emulator that allows you to run just about any version of System/MacOS right in your browser. Now there are limitations to this, but it is really cool that you don't need to set up emulators yourself or hunt down start up disks. You just select an operating system and click 'run' and your off to the races. It even emulates NeXT computers and the NeXT Step operating system. Check it out in the new link in the sidebar!
