#+TITLE: Site News and Weblog
#+DESCRIPTION: In the 1990's things were crazy and you never knew what browser would be best for a site...unless they told you ;)
#+AUTHOR: Jon Saxton
#+HTML_HEAD: <link href="../styles/main.css" rel="stylesheet" type="text/css" />

In the mid to late 1990's, there was a new type of website that popped up. These sites were dedicated to people's opinions or news. We called them weblogs, but this wasn't eventually shortened to just blog. In the modern age, these have largely be replaced by macro-blogs like Twitter or social sites like Facebook, but, before then, the blog was the way to put your opinions out there. Here, I will be putting a my own thoughts about various topics, but this will remain mostly a place for site news.

+ [[file:./blog/11-Feb-2024.org][11 Feb 2024 - Infinite Mac, Infinite Possibilities]]
+ [[file:./blog/15-Sep-2023.org][15 Sep 2023 - This site is up!]]
+ [[file:./blog/06-Sep-2023.org][06 Sep 2023 - Main Site Updates]]
+ [[file:./blog/17-Aug-2023.org][17 Aug 2023 - Images Maps]]
+ [[file:./blog/09-Aug-2023.org][09 Aug 2023 - Guestbook!]]
+ [[file:./blog/04-Aug-2023.org][04 Aug 2023 - Let's Talk About Frames!]]
+ [[file:./blog/28-Jul-2023.org][28 Jul 2023 - Plans for the Site]]
