#+TITLE: A Test Page
#+DESCRIPTION: In the 1990's things were crazy and you never knew what browser would be best for a site...unless they told you ;)
#+AUTHOR: Jon Saxton
#+HTML_HEAD: <link href="../styles/main.css" rel="stylesheet" type="text/css" />

Hello all you awesome people!

This rad page collects some old skool HTML tags and stuff. It is designed to showcase what you could do with HTML back around 1996, the year I had started to learn how to build web sites. Right now it is blank, except this text, as I have to remember some of this stuff. Soon I hope it will be full of awesome stuff though!

The idea of this page is to show you the HTML tags or other code snippets and then show examples of how they would look. Now some of these examples may only work in certain older browsers. If that is the case I'll let you know. In fact, the first one is the ~<marquee>~ tag. This tag only worked in old versions of Internet Explorer.

* The ~<marquee>~ Tag
Internet Explorer 4+ required (or many modern browsers)

#+BEGIN_SRC html
<marquee>This tag just scrolled text on a screen</marquee>
#+END_SRC

#+BEGIN_EXPORT html
<marquee>This tag just scrolled text on a screen</marquee>
#+END_EXPORT

The tag included some attributes, though no one I knew of ever uesed any of them. I'll show a few below, but, for a more detailed list and explinations, you can check out @@html:<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee" target="_new">this page</a>@@.

#+BEGIN_SRC html
<marquee scrollamount="4">This will slow down the scrolling!</marquee>
<marquee direction="right">This text will scroll to the right!</marquee>
<marquee behavior="slide">This changes how the text scrolls!</marquee>
#+END_SRC

#+BEGIN_EXPORT html
<marquee scrollamount="4">This will slow down the scrolling!</marquee>
<marquee direction="right">This text will scroll to the right!</marquee>
<marquee behavior="slide">This changes how the text scrolls!</marquee>
#+END_EXPORT

Of course these attributes can be combined! Be warned though it might get crazy!!

#+BEGIN_SRC html
<marquee behavior="slide" scrollamount="4" direction="right">This might be a little weird!</marquee>
#+END_SRC

#+BEGIN_EXPORT html
<marquee behavior="slide" scrollamount="4" direction="right">This might be a little weird!</marquee>
#+END_EXPORT

* The ~<blink>~ Tag
This is one that we have to be careful with today! Netscape Navigator 4+ may required for the examples to work correctly.

#+BEGIN_SRC html
<blink>This text will only blink in old version of Netscape Navigator</blink>
#+END_SRC

#+BEGIN_EXPORT html
<blink>This text will only blink in old version of Netscape Navigator</blink>
#+END_EXPORT

If the text above is not blinking it's becuase this tag was really only supported by Netscape and, most modern browsers never really supported it. The proper way to make text blink (which may not work in older browsers) uses CSS.

#+BEGIN_SRC html
<style>
@keyframes blink{
  50% {
    opacity: 0;
  }
</style>
<span style="animation:blink 1s linear infinite">This text will blink, but only in modern browsers.</span>
#+END_SRC

#+BEGIN_EXPORT html
<span class="blinky">This text will blink, but only in modern browsers.</span>
#+END_EXPORT

It should be noted that no attributes have been documented for the ~<blink>~ tag. It is likely that none existed or that it did not use any unique attributes. Also, if you want to use this tag and still ensure it works in most modern browsers you could do the following:

#+BEGIN_SRC html
<style>
  blink {animation:blink 1s linear infinite}

@keyframes blink{
  50% {
    opacity: 0;
  }
</style>
<blink>This text will blink, except in ol' Internet Explorer!</blink>
#+END_SRC

#+BEGIN_EXPORT html
<blink class="blinky">This text will blink, except in ol' Internet Explorer!</blink>
#+END_EXPORT

For maximum compatibility, the CSS inside the ~<style>~ tags above should be inside that tag and either nested in the document's ~<head>~ tag or placed in a separate .css file.

* Frames!
One of the most used design tricks in the 1990's was the use of frames. Frames divided a web page into two or more sections and let designers place different web pages in those sections. This was often used to add a static and persistent side bar to a page like how it is used on this site! This meant that users could have a side bar for navigation and that the web designer/developer didn't need to update every single page any time a link was added, edited, or removed. This was the reason I used frames for just about every site I made back in the day. You see if you used an HTML editor like Dreamweaver, this was less needed. Designers would write a template and then each page would link to that template. Updating the template would auto-magically update each page, but, for those of us who had to do everything by hand, this was a bit tedious, so frames were a good thing. They have fallen out of favor now since we have ajax and other methods of updating only portions of a page so they aren't needed any more, but they were very helpful before such technologies existed.

Frames could be simple, like this site, with only two columns or two rows, as shown by the code below taken directly from the main index source of this site:
#+BEGIN_SRC html
  <frameset cols="25%, 75%">
    <frame name="navbar" src="./frames/nav.htm" />
    <frame name="main" src="./frames/home.htm" />
    <noframes>
      <p>This browser does not support frames and is not well-suited for the 1996 experience. It is either too new, or too old. Please use an era-appropriate browser like Netscape Navigator 3</p>
    </noframes>
  </frameset>
#+END_SRC
The ~<noframes>~ tag told browsers what do display if that didn't support frames, this was mostly used by very old browsers or text-only browsers. Most designers would actually put a link to the navigation page or an alternate version of the site made for text-only browsers, or, if they were lazy, just say something like what I have in that example.

Frames could also be extremely complex with multiple rows and columns, as shown here:
#+BEGIN_SRC html
<frameset rows="20px,*,20px" />
  <frame name="top" src="./top.htm" />
  <frameset cols="200px,*,20px" />
    <frame name="navbar" src="./nav.htm" />
    <frame name="main" src="./home.htm" />
    <frame name="right" src="./right.htm" />
  </frameset>
  <frame name="bot" src="./bottom.htm" />
</frameset>
#+END_SRC
I used some pretty complicated frames and some very interesting artistic skills to create some pretty interesting looking sites. I'll see if I can find some and at least give you a screen shot of them, because they were really quite creative, if I do say so myself.

* Image maps
Image maps were an interesting concept. The idea was that you could split parts of an image up and then place hyperlinks in those parts and the user can then click that part of the image and go to another page. I don't have any example of this yet as I didn't use it much except for some navigation buttons placed in a single banner image, but I'll see if I can put up some examples soon and describe this in a bit more detail.
